FROM nginx
RUN apt update && apt install unzip
RUN mkdir /var/www && cd /var/www &&  curl -LON https://github.com/moodle/moodle/archive/refs/heads/MOODLE_400_STABLE.zip && unzip MOODLE_400_STABLE.zip && mv moodle-MOODLE_400_STABLE html && rm MOODLE_400_STABLE.zip
